Template for Fourthwall.
Domain-Connect/Templates pull request #194
Opened 2021-11-19 17:18 UTC by stabarez

Template for Fourthwall users to easily set up DNS records needed to integrate.

2021-11-22 08:51 UTC, pawel-kow requested changes

2021-11-22 08:51 UTC, pawel-kow commented on goentri.com.fourthwall.json
> +      "host": "zendepsk4.support",
typo?

2021-11-22 16:11 UTC, stabarez commented on goentri.com.fourthwall.json
> +      "host": "zendepsk4.support",
good catch @pawel-kow , fixed.

2021-11-23 04:36 UTC, pawel-kow approved these changes
LGTM!

2021-11-23 04:36 UTC, merged