Template for support subdomains: Fourthwall
Domain-Connect/Templates pull request #208
Opened 2022-02-09 17:36 UTC by beholders-eye

Dropping #206 in favor of this one

There's no need to update `goentri.com.fourthwall.json`, just need to add a `.subdomain.json` instead.

2022-02-10 13:50 UTC, pawel-kow requested changes

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "%sendgridHost%.@",
`.@` is not needed here (and likely may be confused by some providers)

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "s1._domainkey.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "s2._domainkey.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk1._domainkey.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk2._domainkey.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk1.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk2.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk3.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendesk4.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "zendeskverification.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "_dmarc.%supportHost%",
remove `.%supportHost%`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "%supportHost%",
replace `%supportHost%` with `@`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "%supportHost%",
replace `%supportHost%` with `@`

2022-02-10 13:50 UTC, pawel-kow commented on goentri.com.fourthwall.subdomain.json
> +         "host": "%supportHost%",
replace `%supportHost%` with `@`

2022-02-15 16:32 UTC, beholders-eye commented
Retrying it again, in a simpler way.

2022-02-15 16:32 UTC, closed without merging