Add 2 templates elementor.com
Domain-Connect/Templates pull request #246
Opened 2022-06-12 15:11 UTC by elementortzvi

Add 2 templates
thanks

2022-06-20 09:23 UTC, yotamselementor commented
@pawel-kow any chance you take a look at this?

2022-06-21 08:12 UTC, pawel-kow requested changes
Sorry for delay in the review. Vacation + sick leave.

2022-06-21 08:12 UTC, pawel-kow commented on elementor.com.website.json
> +   "hostRequired":true,
This template looks like an APEX template, so I think `hostRequired` = false is what you want.

2022-06-21 08:12 UTC, pawel-kow commented on elementor.com.cname.json
> +   "records":[
It's generally useful to add `variableDescription` if there are variables.

2022-06-21 08:12 UTC, pawel-kow commented on elementor.com.website.json
> +   "syncPubKeyDomain": "domainconnect.elementor.com",
It's generally useful to add `variableDescription` if there are variables.

2022-06-22 08:55 UTC, pawel-kow approved these changes
LGTM!

2022-06-22 08:55 UTC, merged

2022-06-22 09:00 UTC, yotamselementor commented
> LGTM!

Thanks @pawel-kow , feel well!