Go Daddy domain connection
Domain-Connect/Templates pull request #271
Opened 2022-10-12 16:20 UTC by emranlatif

Connection to godaddy domains

2022-10-12 16:44 UTC, pawel-kow requested changes

2022-10-12 16:44 UTC, pawel-kow commented on userdashboard.pixely.com.arecord.json
> +    "logoUrl": "https://www.domainconnect.org/wp-content/uploads/2021/06/flywheel-logo.png",
Copy-paste issue with logoUrl?

2022-10-12 16:44 UTC, pawel-kow commented on userdashboard.pixely.com.arecord.json
> +    "version": 2,
Version 1?

2022-10-13 14:10 UTC, emranlatif commented
Hi,

Please add this as a template and let us know. We will than coordinate with
domain providers to make further changes.

{
    "providerId": "userdashboard.pixely.com",
    "providerName": "Pixely",
    "serviceId": "arecord",
    "serviceName": "Managed WordPress Hosting",
    "version": 2,
    "logoUrl": "https://userdashboard.pixely.com/wp-content/plugins/admin-2020/admin/assets/img/LOGO-BLUE.png",
    "description": "Configure ip address for the domain A record.",
    "syncBlock": false,
    "syncPubKeyDomain": "domainconnect.userdashboard.pixely.com",
    "syncRedirectDomain": "userdashboard.pixely.com",
    "records": [
        {
            "type": "A",
            "host": "@",
            "pointsTo": "%ip%",
            "ttl": 3600
        }
    ]
}


Regards,
Imran

On Wed, Oct 12, 2022 at 5:44 PM Pawel Kowalik ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In userdashboard.pixely.com.arecord.json
> <https://github.com/Domain-Connect/Templates/pull/271#discussion_r993690341>
> :
>
> > @@ -0,0 +1,20 @@
> +{
> +    "providerId": "userdashboard.pixely.com",
> +    "providerName": "Pixely",
> +    "serviceId": "arecord",
> +    "serviceName": "Managed WordPress Hosting",
> +    "version": 2,
> +    "logoUrl": "https://www.domainconnect.org/wp-content/uploads/2021/06/flywheel-logo.png",
>
> Copy-paste issue with logoUrl?
> ------------------------------
>
> In userdashboard.pixely.com.arecord.json
> <https://github.com/Domain-Connect/Templates/pull/271#discussion_r993690483>
> :
>
> > @@ -0,0 +1,20 @@
> +{
> +    "providerId": "userdashboard.pixely.com",
> +    "providerName": "Pixely",
> +    "serviceId": "arecord",
> +    "serviceName": "Managed WordPress Hosting",
> +    "version": 2,
>
> Version 1?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Domain-Connect/Templates/pull/271#pullrequestreview-1139421650>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARV4Y2TIJUIOOXULP4WB43WC3TH3ANCNFSM6AAAAAARDOOAIE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-13 14:24 UTC, pawel-kow commented
@emranlatif Please update the pull request with the corrected template, or close this one and open a new.

2022-10-13 14:27 UTC, emranlatif commented
Hi,

Its not allowing me to push the changes from my git. And because of that I
cannot create a PR.

my git email is ***@***.***

Regards,
Imran

On Thu, Oct 13, 2022 at 3:25 PM Pawel Kowalik ***@***.***>
wrote:

> @emranlatif <https://github.com/emranlatif> Please update the pull
> request with the corrected template, or close this one and open a new.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Domain-Connect/Templates/pull/271#issuecomment-1277699110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARV4YZCHLVHITOUNYRRL2LWDALUZANCNFSM6AAAAAARDOOAIE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-13 14:32 UTC, pawel-kow commented
@emranlatif not sure how I can help on this. I guess you need to get access back to your github and update this PR or create a new one.

2022-10-13 14:36 UTC, emranlatif commented
I am getting this when i try to push it

15:34:39.583: [Templates] git -c credential.helper= -c core.quotepath=false
-c log.showSignature=false push --progress --porcelain origin
refs/heads/master:master
remote: Permission to Domain-Connect/Templates.git denied to emranlatif.
fatal: unable to access 'https://github.com/Domain-Connect/Templates.git/':
The requested URL returned error: 403
15:34:41.750: [Templates] git -c credential.helper= -c core.quotepath=false
-c log.showSignature=false push --progress --porcelain origin
refs/heads/master:master
remote: Permission to Domain-Connect/Templates.git denied to emranlatif.
fatal: unable to access 'https://github.com/Domain-Connect/Templates.git/':
The requested URL returned error: 403

On Thu, Oct 13, 2022 at 3:32 PM Pawel Kowalik ***@***.***>
wrote:

> @emranlatif <https://github.com/emranlatif> not sure how I can help on
> this. I guess you need to get access back to your github and update this PR
> or create a new one.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Domain-Connect/Templates/pull/271#issuecomment-1277710297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARV4Y3UJIFTJ5V55JSVXA3WDAMQVANCNFSM6AAAAAARDOOAIE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-13 14:48 UTC, emranlatif commented
I just created a new PR. Please acknowledge.

Regards,
Imran

On Thu, Oct 13, 2022 at 3:36 PM Imran Latif ***@***.***>
wrote:

> I am getting this when i try to push it
>
> 15:34:39.583: [Templates] git -c credential.helper= -c
> core.quotepath=false -c log.showSignature=false push --progress --porcelain
> origin refs/heads/master:master
> remote: Permission to Domain-Connect/Templates.git denied to emranlatif.
> fatal: unable to access 'https://github.com/Domain-Connect/Templates.git/':
> The requested URL returned error: 403
> 15:34:41.750: [Templates] git -c credential.helper= -c
> core.quotepath=false -c log.showSignature=false push --progress --porcelain
> origin refs/heads/master:master
> remote: Permission to Domain-Connect/Templates.git denied to emranlatif.
> fatal: unable to access 'https://github.com/Domain-Connect/Templates.git/':
> The requested URL returned error: 403
>
> On Thu, Oct 13, 2022 at 3:32 PM Pawel Kowalik ***@***.***>
> wrote:
>
>> @emranlatif <https://github.com/emranlatif> not sure how I can help on
>> this. I guess you need to get access back to your github and update this PR
>> or create a new one.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Domain-Connect/Templates/pull/271#issuecomment-1277710297>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AARV4Y3UJIFTJ5V55JSVXA3WDAMQVANCNFSM6AAAAAARDOOAIE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-10-13 14:59 UTC, pawel-kow commented
You should push to your own fork, not to the upstream project

2023-06-07 02:42 UTC, closed without merging