update cname record for chime.me.website.json
Domain-Connect/Templates pull request #348
Opened 2023-03-22 07:14 UTC by lim1208

2023-03-23 06:35 UTC, pawel-kow approved these changes

2023-03-23 06:36 UTC, pawel-kow requested changes

2023-03-23 06:36 UTC, pawel-kow commented on chime.me.website.json
Consider bumping the version number if the template was already deployed somewhere.

2023-03-24 01:01 UTC, lim1208 commented on chime.me.website.json
Thanks. The template is currently not deployed anywhere. I will apply it in the future.

2023-03-24 01:23 UTC, closed without merging