Entri/kajabi template
Domain-Connect/Templates pull request #439
Opened 2023-09-20 23:27 UTC by evelyndearaujo-goentri

2023-09-21 05:43 UTC, pawel-kow requested changes

2023-09-21 05:43 UTC, pawel-kow commented on goentri.com.kajabi.json
> +      "host": "mxb.mailgun.org",
I don't think this would be correct...

2023-09-21 22:36 UTC, evelyndearaujo-goentri commented on goentri.com.kajabi.json
> +      "host": "mxb.mailgun.org",
Thank you @pawel-kow, it's fixed.

2023-09-22 05:02 UTC, pawel-kow approved these changes
lgtm

2023-09-22 05:05 UTC, merged