feat: email isv template
Domain-Connect/Templates pull request #513
Opened 2024-03-26 08:40 UTC by b805rohit

2024-03-26 10:49 UTC, pawel-kow requested changes

2024-03-27 06:54 UTC, b805rohit commented on leadconnectorhq.com.isv-email.json
> +  "serviceId": "email-isv",
updated!

2024-03-27 06:54 UTC, b805rohit commented on leadconnectorhq.com.isv-email.json
> +      "data": "%txtValue2%",
updated!

2024-03-29 06:33 UTC, pawel-kow approved these changes
Lgtm

2024-03-29 06:35 UTC, merged